DROP TABLE IF EXISTS t_fee_collection;  
CREATE TABLE t_fee_collection (  
  collection_id integer NOT NULL AUTO_INCREMENT,  
  order_id integer NOT NULL,  
  order_no varchar(80) NOT NULL,  
  subject varchar(500) NOT NULL, 
  payer_id varchar(20) ,  
  amount DECIMAL(10,2),
  discount DECIMAL(10,2),
  currency_id integer default 1,
  collection_type integer default 1,
  currency_rate DECIMAL(10,2) default 1,
  description varchar(500),
  notify_id varchar(500),
  notify_type varchar(500),
  notify_time varchar(500),
  gmt_create varchar(500),
  gmt_payment varchar(500),
  is_total_fee_adjust varchar(500),
  quantity varchar(500),
  use_coupon varchar(500),
  seller_email varchar(500),
  buyer_email varchar(500),
  seller_id varchar(500),
  buyer_id varchar(500),
  sign varchar(500),
  sign_type varchar(500),
  exterface varchar(500),
  out_trade_no varchar(500),
  trade_no varchar(500),
  status_id integer not null,
  trade_status varchar(500),
  createdate  datetime default NOW(),
  updateddate  datetime default  NOW(),
  PRIMARY KEY (collection_id)  
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;