package com.funeral.kris.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "t_wish_order")
public class WishOrder {

	@Id
	@GeneratedValue
	@Column(name = "wish_order_id")
	private Integer wishOrderId;
	// if payment is done in shopping cart, then payWishOrderId should be same
	// as the one generated by shopping cart . otherwise, it is same with wishOrderId.
	@Column(name = "pay_wish_order_id")
	private Integer payWishOrderId;

	@Column(name = "source_id")
	private Integer sourceId;
	
	
	@Column(name = "pay_method")
	private Integer payMethod;

	public Integer getPayMethod() {
		return payMethod;
	}

	public void setPayMethod(Integer payMethod) {
		this.payMethod = payMethod;
	}

	public Integer getPayWishOrderId() {
		return payWishOrderId;
	}

	public void setPayWishOrderId(Integer payWishOrderId) {
		this.payWishOrderId = payWishOrderId;
	}

	public Integer getSourceId() {
		return sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "user_id")
	private Integer userId;
	
	@Column(name = "status_id")
	private Integer statusId;

	@Column(name = "order_id")
	private Integer orderId;
	
	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "order_no")
	private String orderNo;

	public Integer getStatusId() {
		return statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "price")
	private BigDecimal price;

	@Column(name = "original_price")
	private BigDecimal originalPrice;

	@Column(name = "created_date")
	private Date createdDate;

	@Column(name = "updated_date")
	private Date updatedDate;

	public Integer getWishOrderId() {
		return wishOrderId;
	}

	public void setWishOrderId(Integer wishOrderId) {
		this.wishOrderId = wishOrderId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getOriginalPrice() {
		return originalPrice;
	}

	public void setOriginalPrice(BigDecimal originalPrice) {
		this.originalPrice = originalPrice;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}
